### ISSUE TITLE
It takes a month to run after setting the number of iterations.

### ISSUE THREAD

**Issue by 870627** [michaelspence/LeMaRnsCalibrartionSim#1]
When estimating Uncertain parameters by fitting the model, after setting the number of iterations of 5000, it takes me a month to run. I wonder if this is normal.

**Comment by michaelspence** [comment]
Hi

Are you using the LeMaRns example with only 3 species? This took a day or so to do. However, the Celtic Sea mizer model took about a month. 

Cheers
Mike

**Comment by 870627** [comment]
Thanks.
There is a  uncertain parameters in the LeMaRns model: the recruitment parameter b, which is often referred to as the density-dependent part of the hockey-stick recruitment curve. I'd like to ask you how to obtain the recruitment parameter b.

**Comment by michaelspence** [comment]
This is often done by calibration, although other sources could be used, e.g. from stock-assessments. These references may help:

S2 in https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0227767

Supplementary 1 in https://onlinelibrary.wiley.com/doi/abs/10.1111/faf.12543

We will be publishing this soon that may also help:
https://www.frontiersin.org/articles/10.3389/fmars.2021.700534/abstract

**Comment by 870627** [comment]
I read the paper “LeMaRns: A Length-based Multi-species analysis by numerical simulation in R”, and there is a supplementary file S3, titled “Fitting the North Sea LeMans model to survey and landings data”. Before calibration, the recruitment parameter b  defined in “Evaluation and management implications of uncertainty in a multispecies size-structured model of population and community responses to fishing” can be found in orig_NS_par. I still don't quite understand how to get the specific value of b in orig_NS_par.

**Comment by 870627** [comment]
Hello

I'm using the LeMaRns model and there is a supplementary file S3, titled “Fitting the North Sea LeMans model to survey and landings data”.  Before calibration, the recruitment parameter b can be found in orig_NS_par. But how to get the b value before calibration?

orig_NS_par
## species_names         Linf     W_a     W_b       k        Lmat         a                     
## 1 Sprat                    16.55  0.0059  3.1088  0.681  12.14   885.6667731
## 2 Npout                  23.75  0.0075  3.0244  0.849  17.21   225.0988055
## 3 Sandeel                23.57  0.0049  2.7826  1.000  12.16   231.6879245
## 4 Poor cod              23.00  0.0082  3.0865   0.520  15.00   254.2279144
## 5 Long rough dab   25.00  0.0053  3.1434   0.340  15.00 185.3071561
## 6 Dab                      32.40  0.0159  2.8639   0.536  12.96   69.3184724
## 7 Herring                 33.35  0.0048  3.1984   0.606   23.39  62.1228287
## 8 Horse mackerel    28.00   0.0316  2.6520  0.380   19.00  120.5695838
## 9 Lemon sole           37.00  0.0123  2.9713   0.420   27.00   41.8978427
## 10 Sole                    46.41   0.0089  3.0172   0.284   20.96  17.7411663
## 11 Mackerel            38.00   0.0052  3.1674   0.510   26.00   37.8676686
## 12 Whiting              52.50   0.0099  2.9433   0.323   21.39   11.1149557
## 13 Witch                 44.00   0.0017  3.3887   0.200    29.00   21.71750603
## 14 Gurnard             42.97   0.0160   2.8151   0.266   17.67   23.7587503
## 15 Plaice                 65.32   0.0125   2.9425   0.122   22.22   4.8535417
## 16 Starry ray           66.00   0.0107   2.9400   0.230   46.00   4.6666095
## 17 Haddock            70.65   0.0092   3.0126   0.271   26.91   3.6046815
## 18 Cuckoo ray        92.00   0.0026   3.2169   0.110   59.00   1.3242529
## 19 Monkfish          106.00  0.0297   2.8410   0.180   61.00   0.7738734
## 20 Cod                  149.87  0.0081   3.0502   0.216   54.39   0.2080939
## 21 Saithe               118.94  0.0085   3.0242   0.175   48.61   0.4999956
##              b
## 1   67352.478225
## 2   20821.054248
## 3   57632.695589
## 4   40014.253426
## 5   1710.014437
## 6   3837.179493
## 7   35498.649232
## 8   4672.577765
## 9   208.776950
## 10 320.405464
## 11 1881.553572
## 12 1173.452560
## 13 165.613357
## 14 793.337934
## 15 486.130733
## 16 69.384083
## 17 378.035208
## 18 2.068218
## 19 2.321620
## 20 3.602605
## 21 32.769715

**Comment by michaelspence** [comment]
I believe the parameters b are from the Thorpe et al. 2015 paper:
https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12292

There's no need to know `b` prior to calibration. Initial screening of the parameters should give reasonable initial values. See 
https://www.frontiersin.org/articles/10.3389/fmars.2021.700534/full
and 
faf12543-sup-0001-Supinfo.pdf found here: 
https://onlinelibrary.wiley.com/doi/abs/10.1111/faf.12543
Particularly have a look at the figure at the top of page 7.

**Comment by 870627** [comment]
I want to know whether the parameters b is the inflection point of the hockey-stick spawner–recruit relationship. 
And is there a unit about the parameters b?

**Comment by michaelspence** [comment]
In the hockey-stick spawner-recruit relationship b is the density dependent parameter. See the help files for `rec_hockey`, `rec_const`, `rec_BH`, `rec_linear`, and `rec_Ricker` as well as the other recruitment functions as well as the vignette.
